reddit_on_rails/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session 
  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:index, :new, :create] do 
    resources :comments, only: [:create]
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments, except: [:create]
end

reddit_on_rails/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :bigint(8)        not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  
  validates :title, presence: true 
  validate :valid_content
  
  belongs_to :original_sub,
    foreign_key: :sub_id,
    class_name: :Sub
  
  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs

  belongs_to :author, 
    foreign_key: :author_id, 
    class_name: :User
    
  has_many :comments 
  
  def valid_content
    if (self.url == "" && self.content == "" ) || ( self.url != "" && self.content != "")
      self.errors[:url] << "Invalid content"
    end
  end
  
end

reddit_on_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action only: [:update, :destroy] do 
    require_author(params[:post][:author_id])
  end 

  def new
    @post = Post.new
    @post.sub_id = params[:sub_id]
    @subs = Sub.all
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def edit
    @subs = Sub.all
    @post = Post.find_by(id: params[:id])
    require_author(@post.author_id)
  end

  def create
    @subs = Sub.all 
    @post = Post.new(post_params)
    @post.sub_id = params[:sub_id]
    @post.author_id = current_user.id
    if @post.save
      redirect_to sub_url(@post.sub_id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def update
    @subs = Sub.all
    @post = current_user.posts.find_by(id: params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find_by(id: params[:id])
    if @post.destroy
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      redirect_to posts_url
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
  
end

reddit_on_rails/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_on_rails/app/views/posts/_form.html.erb
<%= auth_token %>

<label>Title: 
  <input type="text" name="post[title]" value="<%=post.title%>">
</label>
<label>URL: 
  <input type="text" name="post[url]" value="<%=post.url%>">
</label>
<label>Content: 
  <input type="text" name="post[content]" value="<%=post.content%>">
</label>
<ul>
  <% subs.each do |sub| %>
    <input type="checkbox" 
      name="post[sub_ids][]" 
      value="<%=sub.id%>"
      <%= "checked" if post.sub_ids.include?(sub.id) %> >
      <%= sub.title %> <br>
  <% end %>
</ul>

reddit_on_rails/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form class="" action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= render 'form', post: @post, subs: @subs %>
  <input type="hidden" name="post[author_id]" value="<%= @post.author_id %>">
  <input type="submit" name="" value="Edit Post">
</form>

reddit_on_rails/app/views/posts/new.html.erb
<h1>New Post</h1>

<form class="" action="<%= sub_posts_url(@post.sub_id) %>" method="post">
  <%= render 'form', post: @post, subs: @subs %>
  <input type="submit" name="" value="Add Post">
</form>

reddit_on_rails/app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<a href="<%= edit_post_url(@post) %>">Edit Post</a> <br>
<% if @post.url.nil? || @post.url.length == 0 %>
  <%= @post.content %>
<% else %>
  <a href="<%= @post.url %>"><%= @post.url %></a>
<% end %>

<h1>Comments</h1>

<form class="" action="<%=post_comments_url(@post)%>" method="post">
  <%= auth_token %>
  <label for="">Comment<br>
    <textarea name="comment[content]" rows="8" cols="80"></textarea>
  </label>
  <input type="submit" name="" value="Add Comment">
</form>

<ul class="no-list-style">
  <% @post.comments.where("parent_comment_id is null").each do |comment| %>
    <li>
      <%= recurse_comments(comment) %>
    </li>
  <% end %>  
</ul>