reddit_on_rails/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session 
  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:index, :new, :create] do 
    resources :comments, only: [:create]
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments, except: [:create]
end

reddit_on_rails/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :bigint(8)        not null, primary key
#  content           :text             not null
#  author_id         :integer          not null
#  post_id           :bigint(8)        not null
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ApplicationRecord
  validates :content, presence: true
  
  belongs_to :post
  
  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User
    
  belongs_to :parent_comment,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    optional: true
    
  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: :Comment
    
end

reddit_on_rails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action only: [:update, :destroy] do 
  #   require_author(params[:author_id])
  # end 
  
  def edit
    @comment = Comment.find_by(id: params[:id])
  end
  
  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]
    @comment.parent_comment_id = params[:comment][:parent_comment_id]
    
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      redirect_to post_url(@comment.post)
    end
  end
  
  def update
    @comment = current_user.comments.find_by(id: params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      redirect_to post_url(@comment.post)
    end
  end
  
  def destroy
    @comment = current_user.comments.find_by(id: params[:id])
    if @comment.destroy
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      redirect_to comments_url
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit(:content)
  end
  
end

reddit_on_rails/app/helpers/comments_helper.rb
module CommentsHelper
end

reddit_on_rails/app/views/comments/_comment.html.erb
<div class="comment" id = "comment-<%=comment.id%>">
  <div class="comment-contents" id="<%="comment-contents-#{comment.id}"%>">
    <div class="bold author"><%= comment.author.username %> wrote: </div>
    <div class="content"><%= comment.content %>  </div>
    <button class="reply-comment-button" 
      id="<%=comment.id%>" 
      type="button" name="button">Reply</button>
    <% if current_user.id == comment.author_id %>
      <button class="edit-comment-button" 
        id="<%=comment.id%>"
        type="button" name="button">Edit</button>
      <form class="delete-comment-button" action="<%=comment_url(comment)%>" method="post">
        <input type="hidden" name="_method" value="delete">
        <%= auth_token %>
        <input type="submit" name="" value="Delete">
      </form>
    <% end %>
    <div class="comment-meta-info">
      <p>Created At: <%= comment.created_at %> Updated At: <%= comment.updated_at %></p> 
    </div>
  </div>
  <form class="edit-comment-form"  
      id="<%="edit-comment-form-#{comment.id}"%>" 
      action="<%=comment_url(comment)%>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="patch">
    <label for="">Comment<br>
      <textarea name="comment[content]" rows="8" cols="80"><%= comment.content %></textarea>
    </label>
    <input type="submit" name="" value="Save Edits">
    <a href="<%=post_url(comment.post)%>">Cancel</a>
  </form>
  <form class="reply-comment-form" 
      id="<%="reply-comment-form-#{comment.id}"%>" 
      action="<%=post_comments_url(comment.post)%>" method="post">
    <%= auth_token %>
    <label for="">Comment<br>
      <textarea name="comment[content]" rows="8" cols="80"></textarea>
    </label>
    <input type="hidden" name="comment[parent_comment_id]" value="<%= comment.id %>">
    <input type="submit" name="" value="Save Edits">
    <a href="<%=post_url(comment.post)%>">Cancel</a>
  </form>
</div>

reddit_on_rails/app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<form action="<%=edit_comment_url(@comment)%>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="patch">
  <label for="content">Content <br>
    <textarea name="comment[content]" rows="8" cols="80">
      <%= comment.content %>
    </textarea>
  </label>
</form>

reddit_on_rails/app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

reddit_on_rails/app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>