reddit_on_rails/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session 
  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:index, :new, :create] do 
    resources :comments, only: [:create]
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments, except: [:create]
end

reddit_on_rails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  
  belongs_to :moderator,
  primary_key: :id,
  foreign_key: :moderator_id,
  class_name: :User
  
  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs

end

reddit_on_rails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  before_action only: [:update, :destroy] do 
    require_author(params[:sub][:moderator_id])
  end 

  def new
    @sub = Sub.new
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find_by(id: params[:id])
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    require_author(@sub.moderator_id)
  end
  
  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end
  
  def update
    @sub = current_user.subs.find_by(id: params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @sub = current_user.subs.find_by(id: params[:id])
    if @sub.destroy
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      redirect_to subs_url
    end
  end
  
  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

reddit_on_rails/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_on_rails/app/views/subs/_form.html.erb
<%= auth_token %>
<label> Title <br>
  <input type="text" name="sub[title]" value="<%= sub.title %>">
</label>
<br>
<label> Description <br>
  <textarea name="sub[description]" rows="8" cols="80"><%= sub.description %></textarea>
</label>

reddit_on_rails/app/views/subs/edit.html.erb
<h1>Edit a sub</h1>

<form class="" action="<%= subs_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= render "form", sub: @sub %>
  <input type="hidden" name="sub[moderator_id]" value="<%= @sub.moderator_id %>">
  <input type="submit" value="Edit Sub">
</form>

<a href="<%= subs_url %>">Back to Index</a>

reddit_on_rails/app/views/subs/index.html.erb
<h1>All the subs</h1>

<a href="<%= new_sub_url %>">New Sub</a>

<ul>
  <% @subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a> 
    </li>
  <% end %>
</ul>

reddit_on_rails/app/views/subs/new.html.erb
<h1>Create a sub</h1>

<form class="" action="<%= subs_url %>" method="post">
  <%= render "form", sub: @sub %>
  <input type="submit" value="Add Sub">
</form>

<a href="<%= subs_url %>">Back to Index</a>

reddit_on_rails/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><%= @sub.description %></p>

<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>
<a href="<%= subs_url %>">Back to Index</a>

<br>
<a href="<%= new_sub_post_url(@sub) %>">Make new Post</a>

<ul>
<% @sub.posts.each do |post| %>
  <li>
    <a href="<%=post_url(post)%>"><%= post.title %></a> 
  </li>  
<% end %>
</ul>